FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN sed -i 's|http://archive.ubuntu.com/ubuntu|http://mirrors.edge.kernel.org/ubuntu|g' /etc/apt/sources.list && \
    apt-get update && apt-get install -y \
    g++-10 cmake make ca-certificates binutils uuid-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /src
